### PR TITLE
fix(package): add `@octokit/core` as peer dependency

### LINKED ISSUE #77: Add @octokit/core as peerDependency
This is a follow up issue to https://github.com/octokit/plugin-paginate-rest.js/issues/124#issuecomment-681019208
    
We need to add `@octokit/core` as a peerDependency to address a problem with yarn 2. It is something I planned to do anyway, but wanted to figure out automated testing to assure compatibility of the plugins with the latest `@octokit/core`.

I only want to define compatibility with the lowest version, in this case v3. Compare pull request https://github.com/octokit/plugin-paginate-rest.js/pull/130/files.

I would appreciate help, this is a great issue for a first-time contributor

### PR DESCRIPTION
**Pull request by HeroicHitesh**
fixes #77

### CODE REVIEW

**Comment by HeroicHitesh** [comment]
@gr2m let me know if I need to remove type from index.ts as per the discussion [here](https://github.com/octokit/plugin-paginate-rest.js/pull/130#issuecomment-689077360)

**Review by gr2m — APPROVED** [review]
Thanks 👍🏼

**Comment by jakebrown58** [comment]
I was upgrading yarn packages today and got this warning:

warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.2" has unmet peer dependency "@octokit/core@>=3".

**Comment by gr2m** [comment]
what `@octokit/rest` version do you use? Can you check if you have any `@octokit/core` version in your dependency tree at all?

**Comment by jakebrown58** [comment]
yea - lerna 3.22.1 -  https://github.com/lerna/lerna/blob/master/package-lock.json
seems to be using octokit/rest 16.35.0.  
though I don't see a reference to octokit/plugin-request-log in the package-lock.json here, which I expected to see.

(Thanks for responding- btw!)

**Comment by jakebrown58** [comment]
Ah - sorry: https://github.com/lerna/lerna/blob/master/utils/github-client/package.json
octokit/rest: 16.28.4

**Comment by gr2m** [comment]
I see. So the problem here is that `@octokit/rest` v16 is not built upon `@octokit/core`. But this plugin utilizes types from `@octokit/core`. 

I think you can probably suppress the warning by installing `@octokit/core` as dev dependency. But the proper fix would be to upgrade `@octokit/rest` to the latest version. Upgrade to v17 first: https://github.com/octokit/rest.js/releases/v17.0.0, address all deprecation messages, then upgrade to v18: https://github.com/octokit/rest.js/releases/v18.0.0

**Comment by jakebrown58** [comment]
Seems to be an issue on lerna's end then, wouldn't you say?   The warning isn't that big of a deal to me.   I mistakenly thought it was blocking me, though turned out to be something else.

**Comment by gr2m** [comment]
I'd say the warning is legit, but in this case safe to ignore. It's only about types anyway, it won't affect your code in production.

**Pull request merged**
